export default class httpStatusUtil {
    private static statusCodeMap: { [key: number]: string } = {
      100: 'Continuar',
      101: 'Mudando Protocolos',
      102: 'Processando',
      200: 'OK',
      201: 'Criado',
      202: 'Aceito',
      203: 'Informação Não Autoritativa',
      204: 'Sem Conteúdo',
      205: 'Redefinir Conteúdo',
      206: 'Conteúdo Parcial',
      207: 'Multi-Status',
      208: 'Já Reportado',
      226: 'IM Usado',
      300: 'Múltipla Escolha',
      301: 'Movido Permanentemente',
      302: 'Encontrado',
      303: 'Ver Outro',
      304: 'Não Modificado',
      305: 'Usar Proxy',
      307: 'Redirecionamento Temporário',
      308: 'Redirecionamento Permanente',
      400: 'Requisição Inválida',
      401: 'Não Autorizado',
      402: 'Pagamento Necessário',
      403: 'Proibido',
      404: 'Não Encontrado',
      405: 'Método Não Permitido',
      406: 'Não Aceitável',
      407: 'Autenticação de Proxy Necessária',
      408: 'Tempo Limite da Requisição',
      409: 'Conflito',
      410: 'Gone',
      411: 'Comprimento Necessário',
      412: 'Pré-condição Falhou',
      413: 'Carga Útil Muito Grande',
      414: 'URI Muito Longa',
      415: 'Tipo de Mídia Não Suportado',
      416: 'Intervalo Não Satisfatório',
      417: 'Expectativa Falhou',
      418: 'Eu sou um bule de chá',
      421: 'Requisição Direcionada',
      422: 'Entidade Não Processável',
      423: 'Fechado',
      424: 'Dependência Falhou',
      425: 'Muito Cedo',
      426: 'Upgrade Necessário',
      428: 'Pré-condição Necessária',
      429: 'Muitas Requisições',
      431: 'Campos de Cabeçalho Muito Grandes',
      451: 'Indisponível por Motivos Legais',
      500: 'Erro Interno do Servidor',
      501: 'Não Implementado',
      502: 'Gateway Ruim',
      503: 'Serviço Indisponível',
      504: 'Tempo Limite do Gateway',
      505: 'Versão HTTP Não Suportada',
      506: 'Variante Também Negocia',
      507: 'Armazenamento Insuficiente',
      508: 'Loop Detectado',
      510: 'Não Estendido',
      511: 'Autenticação de Rede Necessária',
    };
  
    static getStatusDescription(codigo: number): string | undefined {
      return httpStatusUtil.statusCodeMap[codigo];
    }
  }